[package]
name = "cudf-rs"
version = "0.1.0"
authors = ["Andy Grove <andygrove73@gmail.com>"]
edition = "2018"

link = "cudf_c"
build = "build.rs"

[dependencies]
cxx = "0.3"

[build-dependencies]
cxx-build = "0.3"
